version: "3.9"
services:
  app:
    build:
      context: .
    container_name: ecommerce_api
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -b '0.0.0.0' -p 3000"
    ports:
      - "3000:3000"
    volumes:
      - ".:/app"
    depends_on:
      - db
      - redis
    user: root

  db:
    image: postgres:14
    container_name: ecommerce_postgres
    environment:
      POSTGRES_USER: caioprieto
      POSTGRES_PASSWORD: ca23io04
      POSTGRES_DB: ecommerce
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: ecommerce_redis
    restart: always
    ports:
      - "6379:6379"

  # redis:
  #   image: redis:latest
  #   container_name: ecommerce_redis
  #   ports:
  #     - "6379:6379"

volumes:
  postgres_data:
